[package]
name = "parse-references"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom-bibtex = "0.3.0"
derive-from-tags = {path = "../derive-from-tags"}
lazy_static = "1.4.0"
regex = "1.5.6"
